version: "3.7"
x-environment: &default-environment
  VARIANT: bullseye
services:
  devcontainer:
    build: ./
    environment:
      - VARIANT=bullseye
    volumes:
      - ..:/workspace
    user: vscode
    command: sleep infinity
  otel-collector:
    image: otel/opentelemetry-collector:0.68.0
    ports:
      - 4317:4317
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: --config=/etc/otel-collector-config.yaml
  jaeger:
    image: jaegertracing/all-in-one:1.27.0
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
