name: CI workflow

on: [push, pull_request]

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install pyOpenSSL --upgrade
      - run: pip install -r requirements.txt
      - run: pip install coverage
      - run: coverage run -m pytest
      - run: coverage report

  vale:
    name: Run Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.0.1
        with:
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [pre-commit, tests, vale]
    if: ${{ needs.pre-commit.result == 'success' && needs.tests.result == 'success' && needs.vale.result == 'success'}}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.0
        with:
          node-version: 14.18.1
      - name: Release
        run: npx semantic-release@v18.0.0
